# Describes the format for available lorex services
# https://developers.home-assistant.io/docs/dev_101_services/

enable_updates:
  name: Recieve updates from field device
  description: Will enable the entity to receive device updates
  target:
    entity:
      integration: lorex
      domain: binary_sensor

disable_updates:
  name: Disable updates from field device
  description: Will disable field device updates to the entity
  target:
    entity:
      integration: lorex
      domain: binary_sensor

